### ISSUE TITLE
[TASK] Replace `Logger` with `tracing`

### ISSUE THREAD

**Issue by Serial-ATA** [webb-tools/gadget#260]
# Overview

`Logger` is simply a wrapper around `log` with a given ID: https://github.com/webb-tools/gadget/blob/main/common/src/debug_logger.rs

This can be replaced with `tracing`, which would allow us to provide that additional context, while also being able to:

* Stop manually calling `format!()`
* Stop having to pass a struct around everywhere we want logging

**Comment by Tjemmmic** [comment]
@Serial-ATA We had some other code for logging in the past, but it was removed because it wasn't being used. Linking in case it is of use. [Here is a past commit with it](https://github.com/webb-tools/gadget/tree/57159531b7faad94d80ef17dd43f38534e33d0bd/sdk/src/logging)

**Comment by tbraun96** [comment]
If we don't pass around the `Logger` everywhere, we will still end up having to pass relevant vars elsewhere. Make sure, especially for testing, the first data we see is the name of the log (e.g., "Alice", "Bob", "Integration Test", "Blueprint-Manager-Alice", "Gadget-Alice", etc). Otherwise, what we have works and makes it easy and clear to follow. It also allows us to print to a file if needed (we use to have this, but keeping `Logger` allows us to easily do this) to separate logs between all the nodes when debugging. This makes causality easy to follow in a side-by-side comparison.
