### ISSUE TITLE
[TASK] Create `gadget-libp2p`

### ISSUE THREAD

**Issue by shekohex** [webb-tools/gadget#92]
## Minimum features needed

1. A p2p network (using libp2p, runs everywhere)
2. Authenticated.
3. Resilient to malicious nodes on the network.

### Messages specific requirements for Tangle.
5. Messages need to be prefixed w/ a `JobId` and a `RoundId` to prevent replayability of on-chain misbehavior reports.
6. Messages need to be signed by the ROLE key before they hit the wire UNLESS it's a non-restaker job participant.
7. Messages need to be verified by as being an on-chain ROLE key, UNLESS it's a non-restaker job participant.

### Handshake Process
On Connection, each peer needs to share a handshake message, the handshake message is just my `peer_id` + `signature` where the `signature` is the result of signing the `peer_id` using the role key.
Each peer verify will need to recover the signer (`role_key`) from the signed message and verify that they are a valid authority, their proxy account, or external participants (TBD)

In the event that a proxy key is being used for a restaker, there should be a method to quickly check the chain of `proxy key -> role key`

### Restakers Set

On each new session, we update our restakers set by query the on-chain data.

**Comment by drewstone** [comment]
### Feature idea - Libp2p addresses in profiles
If we are putting libp2p addresses in profiles so that peers are identifiable then we need to update our onboarding process. A general flow could be one of the following:
1. Run the gadget and it outputs to the terminal or somewhere these exact details. `CREATE PROFILE w/ LIBP2P ADDRESS `("ip4/...")`
2. Run the gadget and have it submit the additional transaction w/ the libp2p address.

Need more discussion and thought regarding why this is beneficial to our goals.
